### ISSUE TITLE
Cannot download released artifacts anymore

### ISSUE THREAD

**Issue by plokhotnyuk** [evolution-gaming/play-json-tools#22]
https://dl.bintray.com/evolutiongaming/maven/com/evolutiongaming/play-json-jsoniter_2.13/0.9.0/play-json-jsoniter_2.13-0.9.0.pom returns 403 (Forbidden)

**Comment by t3hnar** [comment]
Hi, 
That's because of https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
I'll update readme in a minute, meanwhile please replace
```scala
resolvers += Resolver.bintrayRepo("evolutiongaming", "maven")
```
with
```scala
addSbtPlugin("com.evolution" % "sbt-artifactory-plugin" % "0.0.2")
```

**Comment by t3hnar** [comment]
https://github.com/evolution-gaming/play-json-tools/actions/runs/819948440
