### ISSUE TITLE
FlatFormat don't throw an exception if providing non-existing field

### ISSUE THREAD

**Issue by mkharytonau** [evolution-gaming/play-json-tools#23]
Hi, it's seems like
`fieldNotFound` is always true [here](https://github.com/evolution-gaming/play-json-tools/blob/master/play-json-tools/src/main/scala/com/evolutiongaming/playjsontools/PlayJsonHelper.scala#L281) because `tag.runtimeClass.getField(field)` always throws an exception.
And it's also seems like we should use `!fieldNotFound` [here](https://github.com/evolution-gaming/play-json-tools/blob/master/play-json-tools/src/main/scala/com/evolutiongaming/playjsontools/PlayJsonHelper.scala#L288) (throw an exception if provided field not found and do not, if field is exists).

The main concern for us is this constructor will allow us to use non-existing field to flat by and this will stay unnoticed.

**Comment by Mikita-Kharitonau** [comment]
https://stackoverflow.com/questions/15420968/nosuchfieldexception-when-field-exists
is seems like we need to use `getDeclaredField`
