### ISSUE TITLE
Missing Scala 3 artifacts for play-json-jsoniter

### ISSUE THREAD

**Issue by plokhotnyuk** [evolution-gaming/play-json-tools#29]
![image](https://user-images.githubusercontent.com/890289/202138341-e884d311-785c-4837-8f00-c139165ea33f.png)

**Comment by plokhotnyuk** [comment]
@t3hnar Could you please (re)publish play-json-jsoniter_3 for the latest tag?

**Comment by t3hnar** [comment]
from what I can see `crossScalaVersions := Seq("2.13.8", "2.12.17")` scala 3 is not used for build…

**Comment by plokhotnyuk** [comment]
Scala 3 used only for the play-json-jsoniter sub-project:
```
lazy val `play-json-jsoniter` = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Full)
  .settings(commonSettings)
  .settings(
    crossScalaVersions := Seq("2.13.8", "2.12.17", "3.2.0"),
```

**Comment by t3hnar** [comment]
strange that `release` plugin skipped it, I'll take a look

**Comment by plokhotnyuk** [comment]
I've upgraded benchmarks for JSON parsers to support Scala 3 and would like to test play-json-jsoniter too:
https://plokhotnyuk.github.io/jsoniter-scala/

**Comment by plokhotnyuk** [comment]
Fixed now... Thank you a lot,  @t3hnar!
